<?php

namespace app\Provider;

use kosuha606\VirtualAdmin\Model\Alert;
use kosuha606\VirtualAdmin\Model\Session;
use kosuha606\VirtualModel\Example\MemoryModelProvider;
use kosuha606\VirtualModel\VirtualModelEntity;

class SystemAlertProvider extends MemoryModelProvider
{
    /**
     * @throws \Exception
     */
    public function loadData(): void
    {
        $this->memoryStorage[Alert::class] = [];
        $data = Session::one(['where' => [['=', 'key', 'alerts']]]);

        if ($data->value) {
            $this->memoryStorage[Alert::class] = json_decode($data->value, true);
        }
    }

    /**
     * @param string $modelClass
     * @param mixed $config
     * @return array|mixed
     * @throws \Exception
     */
    protected function findMany($modelClass, $config)
    {
        if (!$this->memoryStorage) {
            $this->loadData();
        }

        return parent::findMany($modelClass, $config); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function type(): string
    {
        return 'system_alert';
    }

    /**
     * @return array|null
     * @throws \Exception
     */
    public function flush(): ?array
    {
        $data = array_map(function($item) {
            return $item->toArray();
        }, $this->persistedModels);

        Session::create([
            'key' => 'alerts',
            'value' => json_encode($data, JSON_UNESCAPED_UNICODE),
        ])->save();

        return parent::flush();
    }

    public function delete(VirtualModelEntity $model): bool
    {
        /** @var Session $alerts */
        $alerts = Session::one(['where' => [['=', 'key', 'alerts']]]);
        $alerts->delete();

        return true;
    }
}
